-- EXERCÍCIO 6 — PostgreSQL + Orange
-- Base didática com erros intencionais para investigação de qualidade de dados.

DROP VIEW IF EXISTS vw_vendas_analise;
DROP TABLE IF EXISTS vendas;
DROP TABLE IF EXISTS produtos;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100),
    cpf VARCHAR(11),
    email VARCHAR(150),
    telefone VARCHAR(20),
    cidade VARCHAR(80),
    estado CHAR(2),
    data_cadastro DATE NOT NULL
);

CREATE TABLE produtos (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR(120),
    categoria VARCHAR(60),
    preco NUMERIC(10,2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE vendas (
    id_venda INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER REFERENCES clientes(id_cliente),
    id_produto INTEGER REFERENCES produtos(id_produto),
    data_venda DATE,
    quantidade INTEGER,
    preco_unitario NUMERIC(10,2),
    desconto_percentual NUMERIC(6,2) DEFAULT 0,
    valor_total NUMERIC(12,2),
    forma_pagamento VARCHAR(30),
    status VARCHAR(20) DEFAULT 'CONCLUIDA'
);

-- 1) CARGA INICIAL CORRETA

INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Ana Souza','11111111101','ana.souza@example.com','11990000001','São Paulo','SP','2025-01-08');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Bruno Lima','11111111102','bruno.lima@example.com','11990000002','São Paulo','SP','2025-01-15');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Carla Mendes','11111111103','carla.mendes@example.com','21990000003','Rio de Janeiro','RJ','2025-01-22');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Daniel Rocha','11111111104','daniel.rocha@example.com','31990000004','Belo Horizonte','MG','2025-01-29');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Elisa Martins','11111111105','elisa.martins@example.com','41990000005','Curitiba','PR','2025-02-05');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Felipe Alves','11111111106','felipe.alves@example.com','51990000006','Porto Alegre','RS','2025-02-12');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Gabriela Costa','11111111107','gabriela.costa@example.com','71990000007','Salvador','BA','2025-02-19');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Henrique Melo','11111111108','henrique.melo@example.com','81990000008','Recife','PE','2025-02-26');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Isabela Nunes','11111111109','isabela.nunes@example.com','85990000009','Fortaleza','CE','2025-03-05');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('João Ribeiro','11111111110','joao.ribeiro@example.com','61990000010','Brasília','DF','2025-03-12');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Karen Freitas','11111111111','karen.freitas@example.com','11990000011','Campinas','SP','2025-03-19');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Lucas Barbosa','11111111112','lucas.barbosa@example.com','31990000012','Uberlândia','MG','2025-03-26');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Mariana Teixeira','11111111113','mariana.teixeira@example.com','21990000013','Niterói','RJ','2025-04-02');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Nicolas Castro','11111111114','nicolas.castro@example.com','41990000014','Londrina','PR','2025-04-09');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Olivia Fernandes','11111111115','olivia.fernandes@example.com','51990000015','Caxias do Sul','RS','2025-04-16');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Paulo Cardoso','11111111116','paulo.cardoso@example.com','11990000016','São Paulo','SP','2025-04-23');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Quezia Moraes','11111111117','quezia.moraes@example.com','71990000017','Feira de Santana','BA','2025-04-30');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Rafael Gomes','11111111118','rafael.gomes@example.com','81990000018','Olinda','PE','2025-05-07');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Sabrina Dias','11111111119','sabrina.dias@example.com','85990000019','Caucaia','CE','2025-05-14');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Tiago Araújo','11111111120','tiago.araujo@example.com','61990000020','Brasília','DF','2025-05-21');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Ursula Pires','11111111121','ursula.pires@example.com','11990000021','Santos','SP','2025-05-28');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Victor Ramos','11111111122','victor.ramos@example.com','31990000022','Contagem','MG','2025-06-04');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Wesley Correia','11111111123','wesley.correia@example.com','21990000023','Petrópolis','RJ','2025-06-11');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Ximena Duarte','11111111124','ximena.duarte@example.com','41990000024','Maringá','PR','2025-06-18');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Yara Monteiro','11111111125','yara.monteiro@example.com','51990000025','Pelotas','RS','2025-06-25');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Zeca Batista','11111111126','zeca.batista@example.com','71990000026','Vitória da Conquista','BA','2025-07-02');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Amanda Lopes','11111111127','amanda.lopes@example.com','81990000027','Jaboatão','PE','2025-07-09');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Bernardo Farias','11111111128','bernardo.farias@example.com','85990000028','Fortaleza','CE','2025-07-16');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Camila Prado','11111111129','camila.prado@example.com','11990000029','Sorocaba','SP','2025-07-23');
INSERT INTO clientes (nome, cpf, email, telefone, cidade, estado, data_cadastro) VALUES ('Diego Neves','11111111130','diego.neves@example.com','61990000030','Brasília','DF','2025-07-30');

INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Notebook Basic','Eletrônicos',2500.00,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Mouse Óptico','Acessórios',49.90,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Teclado Mecânico','Acessórios',219.90,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Monitor 24','Eletrônicos',899.00,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Headset USB','Acessórios',159.90,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Webcam HD','Acessórios',189.90,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('SSD 1TB','Armazenamento',429.00,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Pen Drive 64GB','Armazenamento',59.90,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Cadeira Office','Móveis',799.00,TRUE);
INSERT INTO produtos (nome_produto, categoria, preco, ativo) VALUES ('Mesa Compacta','Móveis',499.00,TRUE);

INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (8,4,'2026-01-03',2,899.00,0.00,1798.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (15,7,'2026-01-05',3,429.00,5.00,1222.65,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (22,10,'2026-01-07',4,499.00,10.00,1796.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (29,3,'2026-01-09',1,219.90,0.00,219.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (6,6,'2026-01-11',2,189.90,0.00,379.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (13,9,'2026-01-13',3,799.00,5.00,2277.15,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (20,2,'2026-01-15',4,49.90,10.00,179.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (27,5,'2026-01-17',1,159.90,0.00,159.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (4,8,'2026-01-19',2,59.90,0.00,119.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (11,1,'2026-01-21',3,2500.00,5.00,7125.00,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (18,4,'2026-01-23',4,899.00,10.00,3236.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (25,7,'2026-01-25',1,429.00,0.00,429.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (2,10,'2026-01-27',2,499.00,0.00,998.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (9,3,'2026-01-29',3,219.90,5.00,626.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (16,6,'2026-01-31',4,189.90,10.00,683.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (23,9,'2026-02-02',1,799.00,0.00,799.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (30,2,'2026-02-04',2,49.90,0.00,99.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (7,5,'2026-02-06',3,159.90,5.00,455.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (14,8,'2026-02-08',4,59.90,10.00,215.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (21,1,'2026-02-10',1,2500.00,0.00,2500.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (28,4,'2026-02-12',2,899.00,0.00,1798.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (5,7,'2026-02-14',3,429.00,5.00,1222.65,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (12,10,'2026-02-16',4,499.00,10.00,1796.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (19,3,'2026-02-18',1,219.90,0.00,219.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (26,6,'2026-02-20',2,189.90,0.00,379.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (3,9,'2026-02-22',3,799.00,5.00,2277.15,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (10,2,'2026-02-24',4,49.90,10.00,179.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (17,5,'2026-02-26',1,159.90,0.00,159.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (24,8,'2026-02-28',2,59.90,0.00,119.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (1,1,'2026-03-02',3,2500.00,5.00,7125.00,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (8,4,'2026-03-04',4,899.00,10.00,3236.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (15,7,'2026-03-06',1,429.00,0.00,429.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (22,10,'2026-03-08',2,499.00,0.00,998.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (29,3,'2026-03-10',3,219.90,5.00,626.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (6,6,'2026-03-12',4,189.90,10.00,683.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (13,9,'2026-03-14',1,799.00,0.00,799.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (20,2,'2026-03-16',2,49.90,0.00,99.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (27,5,'2026-03-18',3,159.90,5.00,455.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (4,8,'2026-03-20',4,59.90,10.00,215.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (11,1,'2026-03-22',1,2500.00,0.00,2500.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (18,4,'2026-03-24',2,899.00,0.00,1798.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (25,7,'2026-03-26',3,429.00,5.00,1222.65,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (2,10,'2026-03-28',4,499.00,10.00,1796.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (9,3,'2026-03-30',1,219.90,0.00,219.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (16,6,'2026-04-01',2,189.90,0.00,379.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (23,9,'2026-04-03',3,799.00,5.00,2277.15,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (30,2,'2026-04-05',4,49.90,10.00,179.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (7,5,'2026-04-07',1,159.90,0.00,159.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (14,8,'2026-04-09',2,59.90,0.00,119.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (21,1,'2026-04-11',3,2500.00,5.00,7125.00,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (28,4,'2026-04-13',4,899.00,10.00,3236.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (5,7,'2026-04-15',1,429.00,0.00,429.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (12,10,'2026-04-17',2,499.00,0.00,998.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (19,3,'2026-04-19',3,219.90,5.00,626.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (26,6,'2026-04-21',4,189.90,10.00,683.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (3,9,'2026-04-23',1,799.00,0.00,799.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (10,2,'2026-04-25',2,49.90,0.00,99.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (17,5,'2026-04-27',3,159.90,5.00,455.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (24,8,'2026-04-29',4,59.90,10.00,215.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (1,1,'2026-05-01',1,2500.00,0.00,2500.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (8,4,'2026-05-03',2,899.00,0.00,1798.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (15,7,'2026-05-05',3,429.00,5.00,1222.65,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (22,10,'2026-05-07',4,499.00,10.00,1796.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (29,3,'2026-05-09',1,219.90,0.00,219.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (6,6,'2026-05-11',2,189.90,0.00,379.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (13,9,'2026-05-13',3,799.00,5.00,2277.15,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (20,2,'2026-05-15',4,49.90,10.00,179.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (27,5,'2026-05-17',1,159.90,0.00,159.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (4,8,'2026-05-19',2,59.90,0.00,119.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (11,1,'2026-05-21',3,2500.00,5.00,7125.00,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (18,4,'2026-05-23',4,899.00,10.00,3236.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (25,7,'2026-05-25',1,429.00,0.00,429.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (2,10,'2026-05-27',2,499.00,0.00,998.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (9,3,'2026-05-29',3,219.90,5.00,626.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (16,6,'2026-05-31',4,189.90,10.00,683.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (23,9,'2026-06-02',1,799.00,0.00,799.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (30,2,'2026-06-04',2,49.90,0.00,99.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (7,5,'2026-06-06',3,159.90,5.00,455.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (14,8,'2026-06-08',4,59.90,10.00,215.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (21,1,'2026-06-10',1,2500.00,0.00,2500.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (28,4,'2026-06-12',2,899.00,0.00,1798.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (5,7,'2026-06-14',3,429.00,5.00,1222.65,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (12,10,'2026-06-16',4,499.00,10.00,1796.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (19,3,'2026-06-18',1,219.90,0.00,219.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (26,6,'2026-06-20',2,189.90,0.00,379.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (3,9,'2026-06-22',3,799.00,5.00,2277.15,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (10,2,'2026-06-24',4,49.90,10.00,179.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (17,5,'2026-06-26',1,159.90,0.00,159.90,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (24,8,'2026-06-28',2,59.90,0.00,119.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (1,1,'2026-06-30',3,2500.00,5.00,7125.00,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (8,4,'2026-07-02',4,899.00,10.00,3236.40,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (15,7,'2026-07-04',1,429.00,0.00,429.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (22,10,'2026-07-06',2,499.00,0.00,998.00,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (29,3,'2026-07-08',3,219.90,5.00,626.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (6,6,'2026-07-10',4,189.90,10.00,683.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (13,9,'2026-07-12',1,799.00,0.00,799.00,'PIX','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (20,2,'2026-07-14',2,49.90,0.00,99.80,'CARTAO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (27,5,'2026-07-16',3,159.90,5.00,455.72,'BOLETO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (4,8,'2026-07-18',4,59.90,10.00,215.64,'DINHEIRO','CONCLUIDA');
INSERT INTO vendas (id_cliente,id_produto,data_venda,quantidade,preco_unitario,desconto_percentual,valor_total,forma_pagamento,status) VALUES (11,1,'2026-07-20',1,2500.00,0.00,2500.00,'PIX','CONCLUIDA');

-- 2) INTRODUÇÃO PROPOSITAL DE PROBLEMAS
-- Dados vazios (3 registros)
UPDATE clientes SET telefone = NULL WHERE id_cliente = 5;
UPDATE clientes SET email = '' WHERE id_cliente = 12;
UPDATE clientes SET cidade = NULL WHERE id_cliente = 21;

-- Valores inválidos (6 registros)
UPDATE clientes SET email = 'email-invalido' WHERE id_cliente = 7;
UPDATE produtos SET preco = -5.00 WHERE id_produto = 4;
UPDATE vendas SET quantidade = 0 WHERE id_venda = 15;
UPDATE vendas SET quantidade = -2 WHERE id_venda = 27;
UPDATE vendas SET desconto_percentual = 150 WHERE id_venda = 42;
UPDATE vendas SET data_venda = DATE '2099-01-01' WHERE id_venda = 63;

-- Duplicidades lógicas (3 cópias extras; cada caso forma um par com o original)
UPDATE clientes SET cpf = (SELECT cpf FROM clientes WHERE id_cliente = 29) WHERE id_cliente = 30;
UPDATE produtos SET nome_produto = (SELECT nome_produto FROM produtos WHERE id_produto = 9),
                    categoria = (SELECT categoria FROM produtos WHERE id_produto = 9),
                    preco = (SELECT preco FROM produtos WHERE id_produto = 9)
WHERE id_produto = 10;
UPDATE vendas v SET
    id_cliente = x.id_cliente, id_produto = x.id_produto, data_venda = x.data_venda,
    quantidade = x.quantidade, preco_unitario = x.preco_unitario,
    desconto_percentual = x.desconto_percentual, valor_total = x.valor_total,
    forma_pagamento = x.forma_pagamento, status = x.status
FROM vendas x WHERE v.id_venda = 100 AND x.id_venda = 99;

-- Inconsistências (4 registros)
UPDATE vendas SET valor_total = 9999.99 WHERE id_venda = 35;
UPDATE vendas SET preco_unitario = 999.00 WHERE id_venda = 50;
UPDATE clientes SET cidade = 'Curitiba', estado = 'SP' WHERE id_cliente = 16;
UPDATE vendas SET status = 'CANCELADA' WHERE id_venda = 70;

-- View amigável para exploração no Orange
CREATE OR REPLACE VIEW vw_vendas_analise AS
SELECT
    v.id_venda, v.data_venda, v.quantidade, v.preco_unitario,
    v.desconto_percentual, v.valor_total, v.forma_pagamento, v.status,
    c.id_cliente, c.nome AS cliente, c.cpf, c.email, c.telefone, c.cidade, c.estado,
    p.id_produto, p.nome_produto, p.categoria, p.preco AS preco_catalogo, p.ativo,
    ROUND((v.quantidade * v.preco_unitario * (1 - v.desconto_percentual / 100.0))::numeric, 2) AS valor_calculado
FROM vendas v
LEFT JOIN clientes c ON c.id_cliente = v.id_cliente
LEFT JOIN produtos p ON p.id_produto = v.id_produto;

-- Conferência das quantidades solicitadas
SELECT 'clientes' AS tabela, COUNT(*) AS quantidade FROM clientes
UNION ALL SELECT 'produtos', COUNT(*) FROM produtos
UNION ALL SELECT 'vendas', COUNT(*) FROM vendas;
